# Each new term in the Fibonacci sequence is 
# generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence 
# hose values do not exceed four million, find the 
# sum of the even-valued terms.


def fib(n):
	fibVal = [1,2]
	for x in range(2,n):
		if (fibVal[x-2] + fibVal[x-1]) < 4000000:
			fibVal.append(fibVal[x-2] + fibVal[x-1])
		else: 
			# print fibVal[x-1]		
			break
	even = []		
	for y in range(0,x):
		if fibVal[y] % 2 ==0:
			even.append(fibVal[y])
	# print even
	print sum(even) 
fib(70)

		
	
